# Generated by Django 4.2.5 on 2023-10-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bottom_text',
            field=models.CharField(default='Enter top text', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='meme_template_id',
            field=models.CharField(default='bilbo', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='top_text',
            field=models.CharField(default='Enter top text', max_length=100),
        ),
    ]
